### ISSUE TITLE
Select default/different audio output & Random audio loss / audio distortion

### ISSUE THREAD

**Issue by bjornstevens** [spocon/spocon#21] opened 2020-09-24 11:54 UTC
**Is your feature request related to a problem? Please describe.**
 -- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
The 'problem' that i have is with my bluetooth. I have set up an autoconnect on my linux server so when i start my bluetooth headset, the default audio device goes to my headset. But i don't hear any audio

**Describe the solution you'd like**
-- A clear and concise description of what you want to happen.
Is there by any chance a possibility to add a audio output device selector? 
I also have snapcast installed, the snapclient there uses the Default Audio Device. Audio works flawless there

**Describe alternatives you've considered**
-- A clear and concise description of any alternative solutions or features you've considered.
I tried all 3 functions and tried changing output with pavucontrol (can't really change a lot in pavucontrol). Still no succes

**Additional context**
-- Add any other context or screenshots about the feature request here.
This is the output device snapcast (snapclient) uses and my bluetooth output is: 
![Screenshot_3](https://user-images.githubusercontent.com/23235234/94141367-e9c2c400-fe6c-11ea-87b0-cc2a11ed04a4.png)

Also a little more context:
My set-up is pretty complex because of functionallity.
I use LedFx to have an led-strip synced to audio, the audio is now only being sent by snapcast but i also would really like spocon (or just spotify in general) to also work with my setup.

If any more info is needed feel free to ask 😄

**Comment by devgianlu** [comment] 2020-09-24 12:39
Have you tried [this](https://github.com/librespot-org/librespot-java/tree/dev/player#audio-output-configuration)?

**Comment by bjornstevens** [comment] 2020-09-24 14:36
I could not really work it out. I think this might has to do with that it is running as a service instead of running in a session.

Because in terminal GUI session i got this result:

![afbeelding](https://user-images.githubusercontent.com/23235234/94159581-00284a00-fe84-11ea-859f-234e4c2d26b0.png)

**Comment by devgianlu** [comment] 2020-09-24 14:38
You can have a look at the service logs to see if the available mixers list is empty.

**Comment by bjornstevens** [comment] 2020-09-24 14:41
Is there any other location where that log file would be? as of now i just get this error:
![afbeelding](https://user-images.githubusercontent.com/23235234/94160307-ca379580-fe84-11ea-9264-06fa0296815f.png)

**Comment by bjornstevens** [comment] 2020-09-24 14:57
Allrighty, i found something out now. Everything runs inside a user profile for me. This is not root or spocon, but my personal account. Root does not have access to the pulseaudio because it runs in my personal user profile. 

Now the issues comes that i cannot get spocon to run without root permissions. Running it as sudo just makes it do completely nothing. 
![afbeelding](https://user-images.githubusercontent.com/23235234/94162358-e9372700-fe86-11ea-9dc2-9afceaba8adf.png)

Any further suggestions on what to do?
thanks!

**Comment by spocon** [comment] 2020-09-24 16:12
you could add the user to group "audio" which than gives you access to pulse server according to 

https://dhole.github.io/post/pulseaudio_multiple_users/

`usermod -aG audio spocon`

**Comment by devgianlu** [comment] 2020-09-24 16:16
Try changing `cache.dir` in the config to somewhere your user can write to.

**Comment by spocon** [comment] 2020-09-24 16:24
never mind my comment , spocon should be in the audio group by default , but you can check with 

`id spocon`

**Comment by spocon** [comment] 2020-09-24 16:27
@bjornstevens you are executing the app with bjorn but the file journal.dat is probably created with the spocon user. if you want to execute the jar file manually with another user you need to change the premissions of /opt/spocon/cache to bjorn:bjorn

**Comment by bjornstevens** [comment] 2020-09-24 18:11
> 
> 
> @bjornstevens you are executing the app with user bjorn but the file journal.dat is probably created with the spocon user. if you want to execute the jar file manually with another user you need to change the premissions of /opt/spocon/cache to bjorn:bjorn
> 
> `chown -R bjorn:bjorn /opt/spocon/cache`

I did that, command works  now and i do get output.

But sometimes it is like earrapingly loud, and other times i don't have any output.

- Earrape loud:
![afbeelding](https://user-images.githubusercontent.com/23235234/94182722-b0587b80-fea1-11ea-9f32-7f09c6421717.png)
- Normal sound:
![afbeelding](https://user-images.githubusercontent.com/23235234/94182894-eac21880-fea1-11ea-970f-8ba030c97a07.png)

The sound level does not change during the songs themselves, but when it switches from track to another one.
My server is connected via the spotify account (not local streaming). Might this cause the issue?

**Comment by devgianlu** [comment] 2020-09-24 18:21
We shall figure out if this is an application issue, could you attach a log and a reproducible example?

**Comment by bjornstevens** [comment] 2020-09-24 18:29
> 
> 
> We shall figure out if this is an application issue, could you attach a log and a reproducible example?

If the command is run via terminal, where will the logs get stored?

I changed the setup from complex to less-complex. 

Now it goes like this

Phone has Server selected as spotify client -> Server running spocon -> Audio goes to default audio device -> Bluetooth headset (has been set as default playback device)

**Comment by bjornstevens** [comment] 2020-09-24 18:33
At the song shown in red it went earrape, all before was clean:
![afbeelding](https://user-images.githubusercontent.com/23235234/94185151-3c1fd700-fea5-11ea-8d72-7348875516ca.png)

**Comment by bjornstevens** [comment] 2020-09-24 18:39
![afbeelding](https://user-images.githubusercontent.com/23235234/94185733-f7487000-fea5-11ea-9ee5-11036e08d20b.png)

and this output again and no sound at all

**Comment by devgianlu** [comment] 2020-09-24 21:37
The no sound issue may be caused by a bad implementation of the gain reduction (which I'll check), no idea because the other song should be that loud. Will try it tomorrow.

**Comment by bjornstevens** [comment] 2020-09-25 08:32
I also want to add that my SpoCon server is in a network that is not the same as all my devices. So i can't do any local streaming, only via the cloud.

**Comment by devgianlu** [comment] 2020-09-25 17:44
Can't reproduce the issue with the given tracks, as @nortuzar pointed out, it's probably random. Could you provide a trace log? (set `logLevel` to `TRACE`)

Seems quite a strange issue as I use the software ~6 hours a day and never experienced this.

**Comment by bjornstevens** [comment] 2020-09-25 17:52
I ran the command how i usually run it now (as user Bjorn):
![afbeelding](https://user-images.githubusercontent.com/23235234/94299924-96ce3700-ff68-11ea-93cb-7677cef4c835.png)



Here is the log file with log level set to trace: at the song 'Put Your Records On by Ritt Momney' i had no sound anymore.
[log.txt](https://github.com/spocon/spocon/files/5284517/log.txt)

**Comment by devgianlu** [comment] 2020-09-25 18:58
The issue is clearly with the normalization data that is extracted from the track. 

During your playback:
> NormalizationData:30 - Loaded normalization data, track_gain: 3.625641E-32, track_peak: 6114151.0, album_gain: 1.5655766E29, album_peak: 2.7591954E-21

Actual values:
> NormalizationData:30 - Loaded normalization data, track_gain: -3.8799973, track_peak: 1.0709343, album_gain: -3.8799973, album_peak: 1.0709343

So when the client sees a `track_peak` so high it lowers the gain so much that you can't hear anything. No idea why the values are wrong. Could you try clearing the cache (just delete the cache directory) and try again? The corruption may be happening on disk.

**Comment by bjornstevens** [comment] 2020-09-25 19:50
It could actually be the disk. It is a Virtual Machine so it has a virtual disk. Any idea's where i could place it otherwise? I have SMB connections to the main server but i guess that won't fix anything. 
Is there maybe any mode to not use cache?

Here the latest log. Last song being the one that got silent
[log.txt](https://github.com/spocon/spocon/files/5285018/log.txt)

**Comment by bjornstevens** [comment] 2020-09-25 19:59
I have now disabled cache, seems to work fine. Will play it now all night and report in 2 hours if it is still stable.

Before like not even 5 songs in it got muted or earraping loud.

All i did was change under [cache] enabled = true to enabled = false

**Comment by bjornstevens** [comment] 2020-09-25 21:06
But might the Virtual Machine part have something to do with it? 
By disabling the cache It works flawless right now! Played around 25 songs right now without any muting or earrape sessions, all was at the exact same sound level.

Here is my config by the way
`### Device type (COMPUTER, TABLET, SMARTPHONE, SPEAKER, TV, AVR, STB, AUDIO_DONGLE, GAME_CONSOLE, CAST_VIDEO, CAST_AUDIO, AUTOMOBILE, WEARABLE, UNKNOWN_SPOTIFY, CAR_THING, UNKNOWN) ###
deviceType = "COMPUTER"
### Device name ###
deviceName = "SR01"
### Device ID (40 chars, leave empty for random)  ###
deviceId = ""
### Log level (OFF, FATAL, ERROR, WARN, INFO, DEBUG, TRACE, ALL) ###
logLevel = "TRACE"
### Preferred locale ###
preferredLocale = "en"

### Cache ###
[cache]
	dir = "./cache/"
	# Cache enabled
	enabled = false
	doCleanUp = true

### Authentication ###
[auth]
	# Credentials file (JSON)
	credentialsFile = "credentials.json"
	# Spotify password (USER_PASS only)
	password = "my_password_is_about_rocket_sience"
	# Spotify authentication blob Base64-encoded (BLOB only)
	blob = ""
	# Whether to store reusable credentials on disk (not a plain password)
	storeCredentials = false
	# Strategy (USER_PASS, ZEROCONF, BLOB, FACEBOOK, STORED)
	strategy = "USER_PASS"
	# Spotify username (BLOB, USER_PASS only)
	username = "...."

### Preload ###
[preload]
	# Preload enabled
	enabled = true

### Proxy ###
[proxy]
	# Basic auth password
	password = ""
	# The proxy hostname
	address = ""
	# The proxy port
	port = 0
	# Whether authentication is enabled on the server
	auth = false
	# The proxy type (HTTP, SOCKS)
	type = "HTTP"
	# Whether the proxy is enabled
	enabled = false
	# Basic auth username
	username = ""

### Zeroconf ###
[zeroconf]
	# Listen on all interfaces (overrides `zeroconf.interfaces`)
	listenAll = true
	# Listen on these interfaces (comma separated list of names)
	interfaces = ""
	# Listen on this TCP port (`-1` for random)
	listenPort = -1

### Time correction ###
[time]
	# Manual time correction in millis
	manualCorrection = 0
	# Time synchronization method (NTP, PING, MELODY, MANUAL)
	synchronizationMethod = "NTP"

### API ###
[api]
	# API port (`api` module only)
	port = 24879
	# API listen interface (`api` module only)
	host = "0.0.0.0"

### Player ###
[player]
	# Whether to apply the Spotify loudness normalisation
	enableNormalisation = true
	# Initial volume (0-65536)
	initialVolume = 65536
	# Release mixer line after set delay (in seconds)
	releaseLineDelay = 20
	# Normalisation pregain in decibels (loud at +6, normal at +3, quiet at -5)
	normalisationPregain = 0.0
	# Output metadata in Shairport Sync format (https://github.com/mikebrady/shairport-sync-metadata-reader)
	metadataPipe = ""
	# Autoplay similar songs when your music ends
	autoplayEnabled = true
	# Preferred audio quality (NORMAL, HIGH, VERY_HIGH)
	preferredAudioQuality = "VERY_HIGH"
	# Audio output device (MIXER, PIPE, STDOUT)
	output = "MIXER"
	# Crossfade overlap time (in milliseconds)
	crossfadeDuration = 0
	# Whether the player should retry fetching a chuck if it fails
	retryOnChunkError = true
	# Mixer/backend search keywords (semicolon separated)
	mixerSearchKeywords = ""
	# Output raw (signed) PCM to this file (`player.output` must be PIPE)
	pipe = ""
	# Log available mixers
	logAvailableMixers = true
	# Number of volume notches
	volumeSteps = 64

`

**Comment by bjornstevens** [comment] 2020-09-25 21:23
I kind of want to make a conclusion for now as it does work fine for me. Only personal issue is that i can't run it as a service but just have to run it local. That's all fine to me because the server nearly never shuts down and user doesn't get logged out.

@devgianlu Please let me know if you need any further info about configuration, files or anything else. I am happy to share that 😃 


@spocon also thanks a lot for making this program and also for the help. 
@devgianlu I also have to say that this is a really good working system! It integrates perfectly in my system now (system consisting of server, home assitant, speakers, @LedFx and of course spotify.)

**Comment by devgianlu** [comment] 2020-09-26 10:34
Just happened to me for the first time.

**Comment by bjornstevens** [comment] 2020-09-26 10:50
> 
> Just happened to me for the first time.

Oh, noo! Same issue/ cause?

**Comment by devgianlu** [comment] 2020-09-27 13:03
> Oh, noo! Same issue/ cause?

Yes, identical behavior. Over more than 100 songs only twice yet.

**Comment by l3d00m** [comment] 2020-10-17 17:11
I have the earrape (very loud and distorted audio) issues as well, I'm not using spocon but librespot java self compiled (currently https://github.com/librespot-org/librespot-java/commit/948f72cc84e4ea0834ac615eb64006314d640f69 ). I'm currently trying to extract any meaningful logs while it's happening, but so far I have noticed nothing except the already posted logs about audio clipping reduction before it happens.

I also can confirm regular hickups (while playing over pipe), but it seems to have gotten a little bit better after I disabled the cache. 

I'll try to come up with some better logs soon but for now I just wanted to confirm @bjornstevens observations. The earrape stuff happened at around 1.5.0 and never before IIRC. A IRL friend of mine has the same earrape stuff happening with librespot 1.5.1 in normal mode (not PIPE).

**Comment by devgianlu** [comment] 2020-10-18 09:20
I cannot get my head around why it has started happening suddenly, the issue must be related to something like time. But what??

**Comment by chris9734** [comment] 2020-10-18 09:29
Same issue, I am also using librespot-java.
I also randomly got the distorted loud sound when manually changing the track.

I disabled volume normalization, the problem is gone for one day now and everything seems to be fine. Before it occured to me approximately every hour.

**Comment by l3d00m** [comment] 2020-10-18 10:00
The problem for me is that the earrape stuff is maybe occurring once per day, so it's really hard to debug. Otherwise I would have used something like git bisect to point the commit at blame out. I'll leave librespot-java running the whole day today and see whether I can provide more helpful information.

**Comment by devgianlu** [comment] 2020-10-18 19:21
> I disabled volume normalization, the problem is gone for one day now and everything seems to be fine. Before it occured to me approximately every hour.

That's a similar workaround as disabling the cache. The data corruption clearly happens in the cache and the normalization data is very fragile as it consists of floating point numbers while missing/corrupted pieces of track will simply be ignored by the Vorbis decoder.

I am currently thinking of including in the metadata table an hash of the first chunk so that the program can invalidate the file if it doesn't match.

**Comment by devgianlu** [comment] 2020-10-18 19:49
I've just pushed the workaround (https://github.com/librespot-org/librespot-java/commit/9ab9f43a91ebbce0e9a3a3c6f3c55a714c756525), haven't tested if it's effective so that everybody here can try it immediately.

**Comment by l3d00m** [comment] 2020-10-18 19:51
Thanks for pushing, trying it out now. Just one q: Is this for the very loud distorted audio or for the occasional hickups or for both?

**Comment by devgianlu** [comment] 2020-10-18 19:52
> Is this for the very loud distorted audio or for the occasional hickups or for both?

This is for the earrape sound. Didn't know there was an issue with hickups, please open an issue on the repo if it persists.

**Comment by l3d00m** [comment] 2020-10-21 21:44
So far I haven't been able to reproduce with cache + volume normalization enabled. Will monitor over the next days.

**Comment by l3d00m** [comment] 2020-11-05 10:58
It seem to have gotten less rare, but after testing for some more time I noticed it still happens every few days. This morning I was able to save one log, but it didn't show anything special. I have volume normalization and cache enabled:
```
Nov 05 11:04:28 raspi-thomas java[4774]: 2020-11-05 11:04:28,579 DEBUG Player:282 - Received command: Transfer
Nov 05 11:04:28 raspi-thomas java[4774]: 2020-11-05 11:04:28,609 DEBUG Player:354 - Loading context (transfer), uri: spotify:playlist:37i9dQZF1E4qKmXOVrQ2OE
Nov 05 11:04:28 raspi-thomas java[4774]: 2020-11-05 11:04:28,613 DEBUG DeviceStateHandler:198 - Device is now active. {ts: 1604570668607}
Nov 05 11:04:28 raspi-thomas java[4774]: 2020-11-05 11:04:28,666 DEBUG PlayerQueueEntry:209 - PlayerQueueEntry{017d18a5372eec67160726661a33d5c7} has been removed from output.
Nov 05 11:04:28 raspi-thomas java[4774]: 2020-11-05 11:04:28,670 INFO  PlayerSession:53 - Created new session. {id: 1tLAIHiaT+ueRXDZ2WVIyg}
Nov 05 11:04:28 raspi-thomas java[4774]: 2020-11-05 11:04:28,677 DEBUG PlayerSession:267 - PlayerQueueEntry{01de02d6266b4a1004b25bf82a14a474} has been added to the output. {sessionId: 1tLAIHiaT+ueRXDZ2WVIyg, pos: 4029, reason: CLICK_ROW}
Nov 05 11:04:28 raspi-thomas java[4774]: 2020-11-05 11:04:28,683 DEBUG TokenProvider:51 - Token expired or not suitable, requesting again. {scopes: [playlist-read], oldToken: StoredToken{expiresIn=3600, accessToken='BQCTdL...EeaJg6', scopes=[playlist-read], timestamp=1604561789345}}
Nov 05 11:04:28 raspi-thomas java[4774]: 2020-11-05 11:04:28,689 DEBUG DealerClient:108 - Handled request. {key: 06cc72dc-8c49-45f5-b452-63199cdb0197, result: SUCCESS}
Nov 05 11:04:28 raspi-thomas java[4774]: 2020-11-05 11:04:28,948 DEBUG EventService:35 - Event sent. {body: 12|37|19|41a5a5490cdd77559b95e36613451b387c8c1d6d|017d18a5372eec67160726661a33d5c7|00000000000000000000000000000000|playlist|trackdone|playlist|endplay|4670072|4539000|4014|4014|361373|18|0|0|0|0|0|0|-1|context|-1|0|1|0|0|0|4014|4014|0|176400|spotify:playlist:37i9dQZF1E4qKmXOVrQ2OE|vorbis|ad90893936c74c6da3ee8868db7e0c54||0|1604526532668|0|context|home|8.5.82.894|com.spotify|crossfade|none|cdc9a9545f7eb7b4a47a7a1658f737f0f907ab1f|na|none, result: 200}
Nov 05 11:04:29 raspi-thomas java[4774]: 2020-11-05 11:04:29,076 DEBUG TokenProvider:55 - Updated token successfully! {scopes: [playlist-read], newToken: StoredToken{expiresIn=3600, accessToken='BQCYZc...Q8cebq', scopes=[playlist-read], timestamp=1604570669071}}
Nov 05 11:04:29 raspi-thomas java[4774]: 2020-11-05 11:04:29,236 DEBUG EventService:35 - Event sent. {body: 10|20|66fa1ac3a0dfc1e71383a28d893136400db51056|017d18a5372eec67160726661a33d5c7|0|0|0|0|0|0|4670072|4539000|music|-1|-1|-1|-1.000000|-1|-1.000000|-1|-1|-1|-1.000000|-1|-1|-1|-1|-1.000000|-1|0.000000|-1.000000|||unknown|0|0|0|0|0|interactive|0|176400|0|0, result: 200}
Nov 05 11:04:29 raspi-thomas java[4774]: 2020-11-05 11:04:29,531 DEBUG EventService:35 - Event sent. {body: 372|1|017d18a5372eec67160726661a33d5c7|spotify:track:5hvIZF56tE8sAwMA9cKmQQ|0|[[0,4014]], result: 200}
Nov 05 11:04:29 raspi-thomas java[4774]: 2020-11-05 11:04:29,621 INFO  DeviceStateHandler:252 - Put state. {ts: 1604570668676, connId: NDFhN...wMTJB, reason: PLAYER_STATE_CHANGED}
Nov 05 11:04:29 raspi-thomas java[4774]: 2020-11-05 11:04:29,780 DEBUG EventService:35 - Event sent. {body: 557|3|1tLAIHiaT+ueRXDZ2WVIyg|spotify:playlist:37i9dQZF1E4qKmXOVrQ2OE|spotify:playlist:37i9dQZF1E4qKmXOVrQ2OE|1604570668667||50|context://spotify:playlist:37i9dQZF1E4qKmXOVrQ2OE, result: 200}
Nov 05 11:04:29 raspi-thomas java[4774]: 2020-11-05 11:04:29,909 INFO  DeviceStateHandler:252 - Put state. {ts: 1604570668681, connId: NDFhN...wMTJB, reason: PLAYER_STATE_CHANGED}
Nov 05 11:04:30 raspi-thomas java[4774]: 2020-11-05 11:04:30,023 DEBUG EventService:35 - Event sent. {body: 558|1|01de02d6266b4a1004b25bf82a14a474|1tLAIHiaT+ueRXDZ2WVIyg|1604570668676, result: 200}
Nov 05 11:04:30 raspi-thomas java[4774]: 2020-11-05 11:04:30,313 DEBUG EventService:35 - Event sent. {body: 274|3|2|2|c1ffbe41407d4a5fb3dca1ef89954178f1c32b3f|spotify:track:6lEpB4jNvF5A1WxCEhRGTy|1|2|2, result: 200}
Nov 05 11:04:30 raspi-thomas java[4774]: 2020-11-05 11:04:30,428 INFO  PlayerQueueEntry:101 - Loaded track. {name: 'Ducktape - Mixed', artists: 'Boris Brejcha', uri: spotify:track:6lEpB4jNvF5A1WxCEhRGTy, id: 01de02d6266b4a1004b25bf82a14a474}
Nov 05 11:04:30 raspi-thomas java[4774]: 2020-11-05 11:04:30,430 DEBUG CrossfadeController:42 - Loaded crossfade intervals {id: 01de02d6266b4a1004b25bf82a14a474, in: {}, out: {}}
Nov 05 11:04:30 raspi-thomas java[4774]: 2020-11-05 11:04:30,763 INFO  DeviceStateHandler:252 - Put state. {ts: 1604570670444, connId: NDFhN...wMTJB, reason: PLAYER_STATE_CHANGED}
Nov 05 11:04:34 raspi-thomas java[4774]: 2020-11-05 11:04:34,305 DEBUG Player:282 - Received command: SkipNext
Nov 05 11:04:34 raspi-thomas java[4774]: 2020-11-05 11:04:34,335 DEBUG CrossfadeController:176 - Changed fade out. {curr: null, custom: false, why: TRACK_DONE, id: 01de02d6266b4a1004b25bf82a14a474}
Nov 05 11:04:34 raspi-thomas java[4774]: 2020-11-05 11:04:34,339 DEBUG CrossfadeController:176 - Changed fade out. {curr: null, custom: false, why: FORWARD_BTN, id: 01de02d6266b4a1004b25bf82a14a474}
Nov 05 11:04:34 raspi-thomas java[4774]: 2020-11-05 11:04:34,343 DEBUG PlayerQueueEntry:209 - PlayerQueueEntry{01de02d6266b4a1004b25bf82a14a474} has been removed from output.
Nov 05 11:04:34 raspi-thomas java[4774]: 2020-11-05 11:04:34,350 DEBUG PlayerSession:267 - PlayerQueueEntry{0102a5ef3b5b8b9a3cd482deeb0bd80f} has been added to the output. {sessionId: 1tLAIHiaT+ueRXDZ2WVIyg, pos: 4, reason: FORWARD_BTN}
Nov 05 11:04:34 raspi-thomas java[4774]: 2020-11-05 11:04:34,365 DEBUG DealerClient:108 - Handled request. {key: 116d8f34-0ade-4f73-a33b-a77134d0ace7, result: SUCCESS}
Nov 05 11:04:34 raspi-thomas java[4774]: 2020-11-05 11:04:34,615 DEBUG EventService:35 - Event sent. {body: 12|37|20|41a5a5490cdd77559b95e36613451b387c8c1d6d|01de02d6266b4a1004b25bf82a14a474|00000000000000000000000000000000|playlist|clickrow|playlist|fwdbtn|655360|4380436|9686|9686|337920|15|0|0|0|1|4045|0|-1|context|267|0|0|0|0|0|9686|9686|0|176400|spotify:playlist:37i9dQZF1E4qKmXOVrQ2OE|vorbis|d09d9173c0bf428eb52d92f58bfdee84||0|1604570668684|0|context|home|8.5.82.894|com.spotify|crossfade|none|cdc9a9545f7eb7b4a47a7a1658f737f0f907ab1f|na|none, result: 200}
Nov 05 11:04:34 raspi-thomas java[4774]: 2020-11-05 11:04:34,660 INFO  DeviceStateHandler:252 - Put state. {ts: 1604570674348, connId: NDFhN...wMTJB, reason: PLAYER_STATE_CHANGED}
Nov 05 11:04:34 raspi-thomas java[4774]: 2020-11-05 11:04:34,896 DEBUG EventService:35 - Event sent. {body: 10|20|c1ffbe41407d4a5fb3dca1ef89954178f1c32b3f|01de02d6266b4a1004b25bf82a14a474|0|0|0|0|0|0|655360|4380436|music|-1|-1|-1|-1.000000|-1|-1.000000|-1|-1|-1|-1.000000|-1|-1|-1|-1|-1.000000|-1|0.000000|-1.000000|||unknown|0|0|0|0|0|interactive|0|176400|0|0, result: 200}
Nov 05 11:04:35 raspi-thomas java[4774]: 2020-11-05 11:04:35,054 INFO  PlayerQueueEntry:101 - Loaded track. {name: 'To the Sea - Einmusik Remix', artists: 'Booka Shade, Eli & Fur, Einmusik', uri: spotify:track:6RCT4geaXTmDmtiwFLJv8j, id: 0102a5ef3b5b8b9a3cd482deeb0bd80f}
Nov 05 11:04:35 raspi-thomas java[4774]: 2020-11-05 11:04:35,055 DEBUG CrossfadeController:42 - Loaded crossfade intervals {id: 0102a5ef3b5b8b9a3cd482deeb0bd80f, in: {}, out: {}}
Nov 05 11:04:35 raspi-thomas java[4774]: 2020-11-05 11:04:35,192 DEBUG EventService:35 - Event sent. {body: 372|1|01de02d6266b4a1004b25bf82a14a474|spotify:track:6lEpB4jNvF5A1WxCEhRGTy|0|[[4045,9686]], result: 200}
Nov 05 11:04:35 raspi-thomas java[4774]: 2020-11-05 11:04:35,366 INFO  DeviceStateHandler:252 - Put state. {ts: 1604570675067, connId: NDFhN...wMTJB, reason: PLAYER_STATE_CHANGED}
Nov 05 11:04:35 raspi-thomas java[4774]: 2020-11-05 11:04:35,486 DEBUG EventService:35 - Event sent. {body: 558|1|0102a5ef3b5b8b9a3cd482deeb0bd80f|1tLAIHiaT+ueRXDZ2WVIyg|1604570674346, result: 200}
Nov 05 11:04:35 raspi-thomas java[4774]: 2020-11-05 11:04:35,772 DEBUG EventService:35 - Event sent. {body: 274|3|2|2|1a9fbef8d3abbd143bbdc62af95d03f59902017a|spotify:track:6RCT4geaXTmDmtiwFLJv8j|1|2|2, result: 200}
```

**Comment by devgianlu** [comment] 2020-11-05 14:49
@l3d00m Did it happen in the middle of the track? Cached tracks should be invalided if a corruption is detected so that isn't the issue.

**Comment by l3d00m** [comment] 2020-11-05 14:52
No, it happened right at the start. 

In the few other cases I had it also always happened right from the start of the track.

**Comment by spocon** [comment] 2020-11-21 12:44
@l3d00m && @chris9734  please check the new version 1.5.2

**Comment by spocon** [comment] 2020-11-21 12:46
its available in 5-10 min from now, depending how fast launchpad is publishing the new version

**Comment by spocon** [comment] 2020-11-25 16:30
Can anyone confirm that the bug is fixed ?

**Comment by kombinatgmbh** [comment] 2020-11-25 16:47
I just stumbled upon this ticket. Few month ago after an spocon update it started to play randomly loud distortion when starting a new song. After few weeks i found that i had in the _/opt/spocon/config.toml_ an other value for **preferredAudioQuality** than VORBIS_96, VORBIS_160 or VORBIS_320. I don't know why there was an other value.
If someone still has random distortion compare your _/opt/spocon/config.toml_ with the values in the README.md.

**Comment by l3d00m** [comment] 2020-11-25 18:10
> Can anyone confirm that the bug is fixed ?

I just compiled the most recent version of librespot-java and will report back in the next days. Thanks for the ping

**Comment by thorstenhaga-tradedoubler** [comment] 2021-01-01 13:51
@l3d00m Can you give us an update to the new versino 1.5.3 ? can I close this ticket ?

**Comment by l3d00m** [comment] 2021-01-01 13:53
@thorstenhaga-tradedoubler I didn't occur again for me, so from my side this can be closed. I will open a new issue in the librespot java repo should it occur again.

Thanks for following up.

**Closed** 2021-01-11 11:32 UTC
Labels: enhancement
